# Generated by Django 4.0.2 on 2022-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
